export const mockLojas = [
  {
    id: "1",
    nome: "Quimx - Matriz",
    cnpj: "12.345.678/0001-90",
    endereco: "Av. Industrial, 1000",
    cidade: "São Paulo",
    estado: "SP",
    telefone: "(11) 3000-0000",
    tipo: "matriz",
    ativo: true,
  },
  {
    id: "2",
    nome: "Quimx - Filial Centro",
    cnpj: "12.345.678/0002-71",
    endereco: "Rua Química, 500",
    cidade: "São Paulo",
    estado: "SP",
    telefone: "(11) 3000-0001",
    tipo: "filial",
    ativo: true,
  },
  {
    id: "3",
    nome: "Quimx - Filial Norte",
    cnpj: "12.345.678/0003-52",
    endereco: "Av. Laboratórios, 2000",
    cidade: "São Paulo",
    estado: "SP",
    telefone: "(11) 3000-0002",
    tipo: "filial",
    ativo: true,
  },
]

export const mockUsers = [
  {
    id: "1",
    nome: "Admin Matriz",
    email: "admin@quimx.com",
    cpf: "111.111.111-11",
    telefone: "(11) 99999-0000",
    role: "admin_matriz",
    lojaId: null,
    ativo: true,
  },
  {
    id: "2",
    nome: "Gerente Centro",
    email: "gerente.centro@quimx.com",
    cpf: "222.222.222-22",
    telefone: "(11) 99999-0001",
    role: "gerente_filial",
    lojaId: "2",
    ativo: true,
  },
  {
    id: "3",
    nome: "Vendedor Centro",
    email: "vendedor.centro@quimx.com",
    cpf: "333.333.333-33",
    telefone: "(11) 99999-0002",
    role: "vendedor",
    lojaId: "2",
    ativo: true,
  },
  {
    id: "4",
    nome: "Gerente Norte",
    email: "gerente.norte@quimx.com",
    cpf: "444.444.444-44",
    telefone: "(11) 99999-0003",
    role: "gerente_filial",
    lojaId: "3",
    ativo: true,
  },
]

export const mockProdutos = [
  {
    id: "1",
    nome: "Ácido Sulfúrico 98%",
    descricao: "Ácido sulfúrico concentrado para uso industrial",
    sku: "QMX-AS-98-001",
    preco: 450.0,
    estoque: 100,
    lojaId: "2",
    ativo: true,
  },
  {
    id: "2",
    nome: "Hidróxido de Sódio (Soda Cáustica)",
    descricao: "Soda cáustica em escamas 99%",
    sku: "QMX-HS-99-002",
    preco: 280.0,
    estoque: 200,
    lojaId: "2",
    ativo: true,
  },
  {
    id: "3",
    nome: "Peróxido de Hidrogênio 50%",
    descricao: "Água oxigenada concentrada para processos industriais",
    sku: "QMX-PH-50-003",
    preco: 320.0,
    estoque: 150,
    lojaId: "2",
    ativo: true,
  },
  {
    id: "4",
    nome: "Acetona PA",
    descricao: "Acetona para análise, grau analítico",
    sku: "QMX-AC-PA-004",
    preco: 180.0,
    estoque: 80,
    lojaId: "3",
    ativo: true,
  },
  {
    id: "5",
    nome: "Etanol 99.5%",
    descricao: "Álcool etílico absoluto",
    sku: "QMX-ET-99-005",
    preco: 220.0,
    estoque: 120,
    lojaId: "2",
    ativo: true,
  },
  {
    id: "6",
    nome: "Cloreto de Sódio PA",
    descricao: "Sal de cozinha purificado para análise",
    sku: "QMX-CS-PA-006",
    preco: 95.0,
    estoque: 300,
    lojaId: "3",
    ativo: true,
  },
]

export const mockFornecedores = [
  {
    id: "1",
    nome: "Química Industrial Ltda",
    setor: "Cosmética",
    cnpj: "98.765.432/0001-10",
    contato: "João Silva",
    telefone: "(11) 4000-0000",
    email: "contato@quimicaindustrial.com",
    ativo: true,
  },
  {
    id: "2",
    nome: "Reagentes Científicos S.A.",
    setor: "Cosmética",
    cnpj: "98.765.432/0002-91",
    contato: "Maria Santos",
    telefone: "(11) 4000-0001",
    email: "vendas@reagentescientificos.com",
    ativo: true,
  },
  {
    id: "3",
    nome: "LabChem Distribuidora",
    setor: "Saneamento",
    cnpj: "98.765.432/0003-72",
    contato: "Carlos Oliveira",
    telefone: "(11) 4000-0002",
    email: "comercial@labchem.com",
    ativo: true,
  },
  {
    id: "4",
    nome: "BioSol Químicos Ltda",
    setor: "Indústria e transformação",
    cnpj: "98.765.432/0004-53",
    contato: "Fernanda Lima",
    telefone: "(11) 4000-0003",
    email: "contato@biosolquimicos.com",
    ativo: true,
  },
  {
    id: "5",
    nome: "TecnoLab Suprimentos",
    setor: "Farmacêutica",
    cnpj: "98.765.432/0005-34",
    contato: "Rafael Almeida",
    telefone: "(11) 4000-0004",
    email: "vendas@tecnolab.com",
    ativo: true,
  },
  {
    id: "6",
    nome: "Higienix Produtos Químicos",
    setor: "Cosmética",
    cnpj: "98.765.432/0006-15",
    contato: "Patrícia Costa",
    telefone: "(11) 4000-0005",
    email: "contato@higienix.com",
    ativo: false,
  },
  {
    id: "7",
    nome: "NanoTech Soluções Industriais",
    setor: "Farmacêutica",
    cnpj: "98.765.432/0007-96",
    contato: "Eduardo Ramos",
    telefone: "(11) 4000-0006",
    email: "suporte@nanotech.com",
    ativo: true,
  },
  {
    id: "8",
    nome: "EcoPurificação Ambiental",
    setor: "Saneamento",
    cnpj: "98.765.432/0008-77",
    contato: "Larissa Duarte",
    telefone: "(11) 4000-0007",
    email: "ambiental@ecopurificacao.com",
    ativo: true,
  },
  {
    id: "9",
    nome: "Reativa Indústria Química",
    setor: "Indústria e transformação",
    cnpj: "98.765.432/0009-58",
    contato: "Gabriel Rocha",
    telefone: "(11) 4000-0008",
    email: "vendas@reativa.com",
    ativo: false,
  },
  {
    id: "10",
    nome: "Alfa Reagentes Ltda",
    setor: "Indústria e transformação",
    cnpj: "98.765.432/0010-39",
    contato: "Juliana Torres",
    telefone: "(11) 4000-0009",
    email: "contato@alfareagentes.com",
    ativo: true,
  },
  {
    id: "11",
    nome: "GlobalChem Importadora",
    setor: "Agroindústria",
    cnpj: "98.765.432/0011-20",
    contato: "Renato Moreira",
    telefone: "(11) 4000-0010",
    email: "import@globalchem.com",
    ativo: true,
  },
  {
    id: "12",
    nome: "PureLab Produtos Analíticos",
    setor: "Farmacêutica",
    cnpj: "98.765.432/0012-01",
    contato: "Sofia Mendes",
    telefone: "(11) 4000-0011",
    email: "atendimento@purelab.com",
    ativo: true,
  },
  {
    id: "13",
    nome: "BioNature Química Verde",
    setor: "Agroindústria",
    cnpj: "98.765.432/0013-82",
    contato: "André Carvalho",
    telefone: "(11) 4000-0012",
    email: "contato@bionature.com",
    ativo: true,
  }
]

export const mockCaixas = [
  {
    id: "1",
    lojaId: "2",
    funcionarioId: "3",
    dataAbertura: new Date().toISOString(),
    dataFechamento: null,
    valorInicial: 500.0,
    valorFinal: null,
    status: "aberto",
  },
]

export const mockVendas = [
  {
    id: "1",
    lojaId: "2",
    caixaId: "1",
    funcionarioId: "3",
    data: new Date().toISOString(),
    itens: [
      {
        produtoId: "2",
        produtoNome: "Hidróxido de Sódio (Soda Cáustica)",
        quantidade: 5,
        precoUnitario: 280.0,
        subtotal: 1400.0,
      },
    ],
    subtotal: 1400.0,
    desconto: 0,
    total: 1400.0,
    formaPagamento: "boleto",
  },
]

export const mockContasPagar = [
  {
    id: "1",
    lojaId: "2",
    descricao: "Aluguel Janeiro",
    valor: 8000.0,
    dataVencimento: "2025-01-10",
    dataPagamento: null,
    categoria: "aluguel",
    status: "pendente",
  },
  {
    id: "2",
    lojaId: "2",
    descricao: "Conta de Energia",
    valor: 1200.0,
    dataVencimento: "2025-01-15",
    dataPagamento: null,
    categoria: "luz",
    status: "pendente",
  },
]
