import { Geist } from "next/font/google";

import "./globals.css";
import "./styles/page.css"

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight:'400'
});

export const metadata = {
  title: "Quimex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geist.variable}`}>
        {children}
      </body>
    </html>
  );
}
